export const UPLOAD_CURRENCIES = 'UPLOAD_CURRENCIES';
export const MAKE_TEMPORARY_CHOICE = 'MAKE_TEMPORARY_CHOICE';
export const ADD_CURRENCY = 'ADD_CURRENCY';
export const DELETE_CURRENCY = 'DELETE_CURRENCY';
export const UPDATE_ADDING_MODAL_STATE = 'UPDATE_ADDING_MODAL_STATE';
export const UPDATE_PORTFOLIO_MODAL_STATE = 'UPDATE_PORTFOLIO_MODAL_STATE';
